In [1]:
import pandas as pd
import numpy as np
import tempfile
import tensorflow as tf

# linus 下面这个包是不是没用？
# from six.moves import urllib

import pandas as pd

In [2]:
data1 = pd.read_pickle('../data/dataV0623.pkl') #这里是数据
train0 = data1.loc[0:11999] #如果把所有训练集放进去一起训练会爆显存那就分一下
train1 = data1.loc[12000:23999]
train = data1.loc[0:51889]
test = data1.loc[51890:64861]

In [3]:
data1.columns

Index(['sex', 'age', 'currentAddress', 'currentPayment', 'postJobName',
       'recommendReason', 'workLonger', 'eduBackground', 'cvkeywords', 'major',
       'jobTracks', 'keyU', 'recommended', 'title', 'location', 'jdkeywords',
       'minEduBackground', 'minWorkYearReq', 'minAnnualSalary',
       'maxWorkYearReq', 'description', 'requirement', 'phase', 'scale',
       'industry', 'benefit', 'label', 'EqualAddress', 'EqualJob', 'Cvs',
       'Jds', 'EqualWord', 'Cvsnum', 'Jdsnum', 'FitEdu'],
      dtype='object')

In [4]:
data1.shape

(64862, 35)

In [5]:
# 每一行是70维的列表
data1['recommendReason']

0        [-1.8090081402864413, 0.3290084377321029, -0.4...
1        [-1.8090081402864413, 0.3290084377321029, -0.4...
2        [-1.7793489433135383, 0.31867071284006326, -0....
3        [-1.7793489433135383, 0.31867071284006326, -0....
4        [-0.4294405618602598, 0.42602468109693004, -0....
                               ...                        
64857    [-0.7449835559970489, -1.9531118859856038, -1....
64858    [-1.35505479333728, -0.8223091095748777, -0.85...
64859    [-1.35505479333728, -0.8223091095748777, -0.85...
64860    [-1.3543210178617888, 0.19608034846962594, 0.5...
64861    [-1.3543210178617888, 0.19608034846962594, 0.5...
Name: recommendReason, Length: 64862, dtype: object

In [6]:
# 每一行是30维的列表
data1['postJobName']

0        [-0.48266388745405814, -0.05315832288594922, -...
1        [-0.48266388745405814, -0.05315832288594922, -...
2        [2.189816649559665, 0.8339484106039369, -0.379...
3        [2.189816649559665, 0.8339484106039369, -0.379...
4        [1.0948469288848115, -0.19021169859424483, 0.2...
                               ...                        
64857    [-0.48266388745405814, -0.05315832288594922, -...
64858    [0.18162245599844842, 0.17212266420660305, -0....
64859    [0.18162245599844842, 0.17212266420660305, -0....
64860    [0.9103477072702192, 0.33535148765569134, -0.3...
64861    [0.9103477072702192, 0.33535148765569134, -0.3...
Name: postJobName, Length: 64862, dtype: object

In [7]:
# 每一行是50维的列表
data1['Cvs']

0        [-2.6323798639569413, -8.362326446566954, 6.59...
1        [-2.6323798639569413, -8.362326446566954, 6.59...
2        [-8.988107651674683, -0.267331026154027, -0.26...
3        [-8.988107651674683, -0.267331026154027, -0.26...
4        [2.976442904804161, 0.6720510893970607, -11.90...
                               ...                        
64857    [-13.29082451775793, 0.1312678930331333, 1.099...
64858    [-12.392731176086242, -0.41109461886050613, 1....
64859    [-12.392731176086242, -0.41109461886050613, 1....
64860    [9.100263135203203, -6.884910335123983, -3.873...
64861    [9.100263135203203, -6.884910335123983, -3.873...
Name: Cvs, Length: 64862, dtype: object

In [8]:
data1

sex       age  currentAddress  currentPayment  \
0      MALE  0.517857               3        0.351719   
1      MALE  0.517857               3        0.351719   
2      MALE  0.625000               2        0.615905   
3      MALE  0.625000               2        0.615905   
4      MALE  0.535714               4        0.683741   
...     ...       ...             ...             ...   
64857  MALE  0.571429               0        1.897499   
64858  MALE  0.517857               0        0.351719   
64859  MALE  0.517857               0        0.351719   
64860  MALE  0.642857               8        0.765310   
64861  MALE  0.642857               8        0.765310   

                                             postJobName  \
0      [-0.48266388745405814, -0.05315832288594922, -...   
1      [-0.48266388745405814, -0.05315832288594922, -...   
2      [2.189816649559665, 0.8339484106039369, -0.379...   
3      [2.189816649559665, 0.8339484106039369, -0.379...   
4      [1.0948469288848115, -0.19021169859424483, 0.2...   
...                                                  ...   
64857  [-0.48266388745405814, -0.05315832288594922, -...   
64858  [0.18162245599844842, 0.17212266420660305, -0....   
64859  [0.18162245599844842, 0.17212266420660305, -0....   
64860  [0.9103477072702192, 0.33535148765569134, -0.3...   
64861  [0.9103477072702192, 0.33535148765569134, -0.3...   

                                         recommendReason  workLonger  \
0      [-1.8090081402864413, 0.3290084377321029, -0.4...    0.068182   
1      [-1.8090081402864413, 0.3290084377321029, -0.4...    0.068182   
2      [-1.7793489433135383, 0.31867071284006326, -0....    0.272727   
3      [-1.7793489433135383, 0.31867071284006326, -0....    0.272727   
4      [-0.4294405618602598, 0.42602468109693004, -0....    0.181818   
...                                                  ...         ...   
64857  [-0.7449835559970489, -1.9531118859856038, -1....    0.136364   
64858  [-1.35505479333728, -0.8223091095748777, -0.85...    0.113636   
64859  [-1.35505479333728, -0.8223091095748777, -0.85...    0.113636   
64860  [-1.3543210178617888, 0.19608034846962594, 0.5...    0.272727   
64861  [-1.3543210178617888, 0.19608034846962594, 0.5...    0.272727   

      eduBackground                                         cvkeywords major  \
0                本科  [1.167181915595595, 0.7402713343413235, -0.002...   自动化   
1                本科  [1.167181915595595, 0.7402713343413235, -0.002...   自动化   
2                本科  [-0.27545664632821076, 0.20010831589142028, 0....    其他   
3                本科  [-0.27545664632821076, 0.20010831589142028, 0....    其他   
4                大专  [-1.08261333362462, 0.794929018900652, -0.3579...    经济   
...             ...                                                ...   ...   
64857            本科  [0.8429836524337201, -0.8855575459945638, 0.44...   自动化   
64858            本科  [0.06296053054116177, -0.6449975331043984, -0....   自动化   
64859            本科  [0.06296053054116177, -0.6449975331043984, -0....   自动化   
64860            本科  [0.2606613165868207, 0.34500196688305246, 1.04...    管理   
64861            本科  [0.2606613165868207, 0.34500196688305246, 1.04...    管理   

       ...                                            benefit label  \
0      ...  [2.28408191352732, 3.1790636116043856, -1.1752...     1   
1      ...  [-0.8078333176741346, 0.10183298300898035, 0.1...     0   
2      ...  [-0.8078333176741346, 0.10183298300898035, 0.1...     1   
3      ...  [1.8133310443946342, -0.1626848538637713, 0.39...     0   
4      ...  [-0.028005999236623502, -0.4466591456950586, -...     1   
...    ...                                                ...   ...   
64857  ...  [-0.8078333176741346, 0.10183298300898035, 0.1...     0   
64858  ...  [1.8133310443946342, -0.1626848538637713, 0.39...     1   
64859  ...  [-0.06070086582281843, -0.32470569919613623, -...     0   
64860  ...  [-0.02800599923662349, -0.4466591456950585, -0...     

In [9]:
data1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 64862 entries, 0 to 64861
Data columns (total 35 columns):
 #   Column            Non-Null Count  Dtype  
---  ------            --------------  -----  
 0   sex               64862 non-null  object 
 1   age               64862 non-null  float64
 2   currentAddress    64862 non-null  int32  
 3   currentPayment    64862 non-null  float64
 4   postJobName       64862 non-null  object 
 5   recommendReason   64862 non-null  object 
 6   workLonger        64862 non-null  float64
 7   eduBackground     64862 non-null  object 
 8   cvkeywords        64862 non-null  object 
 9   major             64862 non-null  object 
 10  jobTracks         64862 non-null  object 
 11  keyU              64862 non-null  object 
 12  recommended       64862 non-null  object 
 13  title             64862 non-null  object 
 14  location          64862 non-null  int32  
 15  jdkeywords        64862 non-null  object 
 16  minEduBackground  64862 non-null  object

In [10]:
flags = tf.app.flags
FLAGS = flags.FLAGS
tf.app.flags.DEFINE_string('f','','kernel')

flags.DEFINE_string("model_dir", "../modelV0624", "Base directory for output models.") #模型输出路径
flags.DEFINE_integer("train_steps", 2000, "Number of training steps.") #训练次数，之前在3w的数据集上这个比较合适

#linus 这里并没有使用data1的全部列
COLUMNS = ['sex', 'age', 'currentAddress', 'currentPayment', 'postJobName', 'recommendReason',
           'workLonger', 'eduBackground', 'cvkeywords', 'major', 'recommended', 'keyU', 'jobTracks',
           'title', 'location', 'jdkeywords', 'minEduBackground', 'minWorkYearReq', 'minAnnualSalary',
           'maxWorkYearReq', 'description', 'requirement', 'phase', 'scale', 'industry', 'benefit', 'EqualAddress', 'EqualJob', 'Cvs',
       'Jds', 'EqualWord', 'FitEdu'] # 所有的特征

LABEL_COLUMN = "label"

#linus 这里的离散特征包括：字符串、数字和布尔值
CATEGORICAL_COLUMNS = ['sex',  'currentAddress',  
            'eduBackground', 'major', 'recommended', 'keyU',
            'minEduBackground',   'phase', 'FitEdu'] #离散特征

#linus 竟然有这么多向量特征 
ARRAY_COLUMNS = ['postJobName', 'recommendReason',
            'cvkeywords','jobTracks',
           'title', 'location', 'jdkeywords','description', 'requirement','industry', 'benefit', 'Cvs',
       'Jds'] #使用bags of word向量化，并进行降维的特征

#linus 
CONTINUOUS_COLUMNS = ['age', 'currentPayment', 'workLonger', 'minWorkYearReq', 'minAnnualSalary',
           'maxWorkYearReq', 'scale', 'EqualAddress', 'EqualJob', 'EqualWord'] #连续数值特征

In [16]:
data1[CATEGORICAL_COLUMNS]

sex  currentAddress eduBackground major recommended   keyU  \
0      MALE               3            本科   自动化       False  False   
1      MALE               3            本科   自动化       False  False   
2      MALE               2            本科    其他        True   True   
3      MALE               2            本科    其他        True   True   
4      MALE               4            大专    经济        True  False   
...     ...             ...           ...   ...         ...    ...   
64857  MALE               0            本科   自动化        True  False   
64858  MALE               0            本科   自动化        True  False   
64859  MALE               0            本科   自动化        True  False   
64860  MALE               8            本科    管理        True   True   
64861  MALE               8            本科    管理        True   True   

      minEduBackground phase FitEdu  
0                   本科    未知   True  
1                   本科    未知   True  
2                   本科    B轮   True  
3                   本科    未知   True  
4                   大专    未知   True  
...                ...   ...    ...  
64857               硕士    未知  False  
64858               本科    未知   True  
64859               大专   已上市   True  
64860               大专    未知   True  
64861               本科    未知   True  

[64862 rows x 9 columns]

In [17]:
data1[CONTINUOUS_COLUMNS]

age  currentPayment  workLonger  minWorkYearReq  minAnnualSalary  \
0      0.517857        0.351719    0.068182             0.3            0.030   
1      0.517857        0.351719    0.068182             0.0            0.030   
2      0.625000        0.615905    0.272727             0.0            0.030   
3      0.625000        0.615905    0.272727             0.0            0.010   
4      0.535714        0.683741    0.181818             1.0            0.060   
...         ...             ...         ...             ...              ...   
64857  0.571429        1.897499    0.136364             0.0            0.030   
64858  0.517857        0.351719    0.113636             0.0            0.009   
64859  0.517857        0.351719    0.113636             0.5            0.020   
64860  0.642857        0.765310    0.272727             1.0            0.060   
64861  0.642857        0.765310    0.272727             0.8            0.036   

       maxWorkYearReq     scale EqualAddress  EqualJob  EqualWord  
0            0.050505  0.011147        False  0.000000   0.015319  
1            1.000000  0.001115        False  0.000000   0.032340  
2            1.000000  0.001115        False  0.214286   0.011631  
3            1.000000  0.222936        False  0.000000   0.005390  
4            1.000000  0.001115        False  0.000000   0.006809  
...               ...       ...          ...       ...        ...  
64857        1.000000  0.000111        False  0.000000   0.000000  
64858        1.000000  0.001115         True  0.000000   0.017021  
64859        1.000000  0.222936        False  0.000000   0.004823  
64860        1.000000  0.001115        False  0.000000   0.008227  
64861        0.353535  0.000111        False  0.000000   0.011348  

[64862 rows x 10 columns]

In [19]:
#linus location不是向量特征吧
data1[ARRAY_COLUMNS]

postJobName  \
0      [-0.48266388745405814, -0.05315832288594922, -...   
1      [-0.48266388745405814, -0.05315832288594922, -...   
2      [2.189816649559665, 0.8339484106039369, -0.379...   
3      [2.189816649559665, 0.8339484106039369, -0.379...   
4      [1.0948469288848115, -0.19021169859424483, 0.2...   
...                                                  ...   
64857  [-0.48266388745405814, -0.05315832288594922, -...   
64858  [0.18162245599844842, 0.17212266420660305, -0....   
64859  [0.18162245599844842, 0.17212266420660305, -0....   
64860  [0.9103477072702192, 0.33535148765569134, -0.3...   
64861  [0.9103477072702192, 0.33535148765569134, -0.3...   

                                         recommendReason  \
0      [-1.8090081402864413, 0.3290084377321029, -0.4...   
1      [-1.8090081402864413, 0.3290084377321029, -0.4...   
2      [-1.7793489433135383, 0.31867071284006326, -0....   
3      [-1.7793489433135383, 0.31867071284006326, -0....   
4      [-0.4294405618602598, 0.42602468109693004, -0....   
...                                                  ...   
64857  [-0.7449835559970489, -1.9531118859856038, -1....   
64858  [-1.35505479333728, -0.8223091095748777, -0.85...   
64859  [-1.35505479333728, -0.8223091095748777, -0.85...   
64860  [-1.3543210178617888, 0.19608034846962594, 0.5...   
64861  [-1.3543210178617888, 0.19608034846962594, 0.5...   

                                              cvkeywords  \
0      [1.167181915595595, 0.7402713343413235, -0.002...   
1      [1.167181915595595, 0.7402713343413235, -0.002...   
2      [-0.27545664632821076, 0.20010831589142028, 0....   
3      [-0.27545664632821076, 0.20010831589142028, 0....   
4      [-1.08261333362462, 0.794929018900652, -0.3579...   
...                                                  ...   
64857  [0.8429836524337201, -0.8855575459945638, 0.44...   
64858  [0.06296053054116177, -0.6449975331043984, -0....   
64859  [0.06296053054116177, -0.6449975331043984, -0....   
64860  [0.2606613165868207, 0.34500196688305246, 1.04...   
64861  [0.2606613165868207, 0.34500196688305246, 1.04...   

                                               jobTracks  \
0      [-1.9150278958625544, -6.792453468807752, 6.22...   
1      [-1.9150278958625544, -6.792453468807752, 6.22...   
2      [-7.259825337234156, -0.3713122640714135, 0.45...   
3      [-7.259825337234156, -0.3713122640714135, 0.45...   
4      [2.7694400375850896, 0.5289529777578527, -10.3...   
...                                                  ...   
64857  [-11.630937353625706, 0.11670395160133842, 0.1...   
64858  [-10.458194993873358, -0.15959376844100553, 1....   
64859  [-10.458194993873358, -0.15959376844100553, 1....   
64860  [9.894924602951006, -7.465664624381204, -4.106...   
64861  [9.894924602951006, -7.465664624381204, -4.106...   

                                                   title  location  \
0      [-0.06581817526815212, -0.2582754350171126, -0...         1   
1      [-0.17146340886173175, -0.6126492696902689, 0....        18   
2      [-0.5982956517356499, 0.4806129375569931, 0.98...         4   
3      [0.7225371329570673, 0.14313984730219875, -0.0...         7   
4      [-0.17146340886173175, -0.6126492696902689, 0....         2   
...                                                  ...       ...   
64857  [-0.71327548651836, 0.6106170450792798, -0.016...        30   
64858  [0.7254875244156066, 0.14325088617051676, -0.0...         0   
64859  [-0.059730052436597576, -0.2234638006687755, -...         9   
64860  [-0.17146340886173175, -0.6126492696902689, 0....         2   
64861  [-0.059730052436597576, -0.2234638006687755, -...        30   

                                              jdkeywords  \
0      [-0.18019532968160115, 0.10613480823796229, 0....   
1      [-0.1275503063230647, -0.2817279011250854, 0.2...   
2      [-0.18019532968160115, 0.10613480823796229, 0....   
3      [0.5823891059867838, 0.008792656576124446, -0....   
4      [-0.143250423

In [13]:
#linus 查看正负样本个数
data1[LABEL_COLUMN].value_counts()

1    32431
0    32431
Name: label, dtype: int64

In [98]:
# linus 单列不同的值
data1['major'].unique()

array(['自动化', '其他', '经济', '会计', '管理', '物理', '计算机', '数学', '车辆', '金融', '语言',
       '经管', '医药', '建筑', '材料', '信息', '电子', '法学', '艺术', '机械', '仪器', '统计',
       '工业工程', '化学', '心理', '食品', '环境', '生物', '土木', '新闻', '能动'],
      dtype=object)

In [14]:
# linus 单列去重
#data1['sex'].drop_duplicates()
data1['sex'].value_counts()

MALE       47288
FEMALE     15672
UNKNOWN     1902
Name: sex, dtype: int64

In [15]:
47288+15672+1902

64862

In [20]:
# linus通过对比可以发现data1比COLUMNS多了3列：Cvsnum、Jdsnum、label
COLUMNS.sort()
print(COLUMNS)
print(len(COLUMNS))
a = list(data1.columns)
a.sort()
print(a)
print(len(a))

['Cvs', 'EqualAddress', 'EqualJob', 'EqualWord', 'FitEdu', 'Jds', 'age', 'benefit', 'currentAddress', 'currentPayment', 'cvkeywords', 'description', 'eduBackground', 'industry', 'jdkeywords', 'jobTracks', 'keyU', 'location', 'major', 'maxWorkYearReq', 'minAnnualSalary', 'minEduBackground', 'minWorkYearReq', 'phase', 'postJobName', 'recommendReason', 'recommended', 'requirement', 'scale', 'sex', 'title', 'workLonger']
32
['Cvs', 'Cvsnum', 'EqualAddress', 'EqualJob', 'EqualWord', 'FitEdu', 'Jds', 'Jdsnum', 'age', 'benefit', 'currentAddress', 'currentPayment', 'cvkeywords', 'description', 'eduBackground', 'industry', 'jdkeywords', 'jobTracks', 'keyU', 'label', 'location', 'major', 'maxWorkYearReq', 'minAnnualSalary', 'minEduBackground', 'minWorkYearReq', 'phase', 'postJobName', 'recommendReason', 'recommended', 'requirement', 'scale', 'sex', 'title', 'workLonger']
35


In [21]:
# Cvsnum和Jdsnum是什么？
data1[['Cvsnum', 'Jdsnum', 'label']]

Cvsnum    Jdsnum  label
0      0.098091  0.264808      1
1      0.098091  0.243902      0
2      0.046605  0.261324      1
3      0.046605  0.303136      0
4      0.094541  0.052265      1
...         ...       ...    ...
64857  0.035064  0.006969      0
64858  0.033733  0.184669      1
64859  0.033733  0.282230      0
64860  0.221926  0.052265      1
64861  0.221926  0.135889      0

[64862 rows x 3 columns]

In [40]:
data1['age'].values

array([0.51785714, 0.51785714, 0.625     , ..., 0.51785714, 0.64285714,
       0.64285714])

In [41]:
data1['age'].size

64862

In [43]:
# python交互式命令行执行ok
# model_dir = tempfile.mkdtemp() if not FLAGS.model_dir else FLAGS.model_dir
# print("model dir = %s" % model_dir)
# model dir = ./modelV0624

# 只要创建一个临时文件夹就可以，既然jupyter执行会报错，就直接跳过去，不影响核心目标。
model_dir = tempfile.mkdtemp() if not '../modelV0624' else '../modelV0624'
print("model dir = %s" % model_dir)


model dir = ../modelV0624


In [ ]:
'''
# 定义Estimator需要实现train、evaluate和predict函数
model = tf.estimator.Estimator(model_fn=model_fn, model_dir=checkpoint_dir, params=model_paras, config=config)

# 实现了Estimator之后，才能实现train_and_evaluate函数
tf.estimator.train_and_evaluate(model,
                                tf.estimator.TrainSpec(
                                    input_fn=lambda: input_fn(tr_files, feature_conf, label_conf,
                                                                num_epochs=FLAGS.epoch,
                                                                batch_size=FLAGS.batch)),
                                tf.estimator.EvalSpec(
                                    input_fn=lambda: input_fn(va_files, feature_conf, label_conf,
                                                                num_epochs=1,
                                                                batch_size=FLAGS.batch,
                                                                shuffle_size=0),
                                    steps=4000, start_delay_secs=30, throttle_secs=60))


'''

In [42]:
    
def col2arr(data,col):
    slist = []
    for i in tuple(data.index):
        slist.append(np.array(data.loc[i,col]))
    return np.array(slist)

# 重要函数
# batch_size是在input_fn定义时指定，这里没有指定，那么默认一个batch就是全量数据
# 这个函数需要优化：batch_size、shuffle等参数设定
def input_fn(df):
    continuous_cols = {k: tf.constant(df[k].values) for k in CONTINUOUS_COLUMNS}
    array_cols = {k: tf.constant(col2arr(df,k)) for k in ARRAY_COLUMNS}
    categorical_cols = {k: tf.SparseTensor(indices=[[i,0] for i in range( df[k].size)], values = df[k].values, dense_shape=[df[k].size,1]) for k in CATEGORICAL_COLUMNS}
    
    feature_cols = dict(continuous_cols)
    feature_cols.update(categorical_cols)
    feature_cols.update(array_cols)
    
    label = tf.constant(df[LABEL_COLUMN].values)

    return feature_cols, label

'''
Overfitting: In order to avoid overfitting, 
it is recommended to set up the training input_fn to shuffle the training data properly.

# Input pipeline for train and evaluate.
def train_input_fn(): # returns x, y
  # please shuffle the data.
  pass
def eval_input_fn(): # returns x, y
  pass
'''

In [24]:
CATEGORICAL_COLUMNS = ['sex',  'currentAddress',  
            'eduBackground', 'major', 'recommended', 'keyU',
            'minEduBackground',   'phase', 'FitEdu'] #离散特征

ARRAY_COLUMNS = ['postJobName', 'recommendReason',
            'cvkeywords','jobTracks',
           'title', 'location', 'jdkeywords','description', 'requirement','industry', 'benefit', 'Cvs',
       'Jds'] #使用bags of word向量化，并进行降维的特征

CONTINUOUS_COLUMNS = ['age', 'currentPayment', 'workLonger', 'minWorkYearReq', 'minAnnualSalary',
           'maxWorkYearReq', 'scale', 'EqualAddress', 'EqualJob', 'EqualWord'] #连续数值特征

### categorical中 类别较少的有：
* sex
* currentAddress
* eduBackground 
* major 
* recommended 
* keyU 
* minEduBackground 
* phase

### linus 这些列表特征后面显示的数字是啥意思？
pJN: 100, rR: 853, cvK: 853, jobT: 853, title: 100, location&currentAddress: 24, jdK: 853, des: 853, requirement: 853, industry: 25, benefit: 18

### linus 清华这里貌似没有使用tfidf生成文本向量
recommendReason cvKeyword jobTracks jdKeyword description requrement使用的是一个字典去统计词频<br>
postJobName title使用的是一个字典<br>
industry benefit各自使用一个字典<br>
逻辑是：首先把使用同一个字典的文本进行分词，然后加总统计词频。在选出高频关键词后统计每个关键词的频率记为向量。<br>
然后统计cv中和jd中关键词的重复数量，其中Cvs和Jds分别是关键词在recommendReason cvKeyword jobTracks；jdKeyword description requrement中出现的向量。<br>
第一个字典记为EqualWord，第二个字典记为EqualJob。<br>
此外，貌似Address的意义不大，可以只是统计cv和jd中currentAddress和location是否有重复<br>

In [44]:
# 将类别特征变成onehot
sex = tf.feature_column.categorical_column_with_vocabulary_list("sex", ['MALE', 'FEMALE', 'UNKNOWN'])
eduBackground = tf.feature_column.categorical_column_with_vocabulary_list('eduBackground', ['高中', '大专', '硕士', '本科', '中专', 'Unknown', '专科', '博士'])
major = tf.feature_column.categorical_column_with_vocabulary_list('major', ['其他', '统计', '自动化', '建筑', '新闻', '土木', '物理', '数学', '材料', '化学', '计算机', '工业工程', '能动', '语言', '会计', '金融', '艺术', '管理', '经管', '食品', '法学', '信息', '环境', '电子', '机械', '医药', '车辆', '生物', '经济', '仪器', '心理'])
recommended = tf.feature_column.categorical_column_with_vocabulary_list('recommended', ['True', 'False'])
keyU = tf.feature_column.categorical_column_with_vocabulary_list('keyU', ['True', 'False'])
FitEdu = tf.feature_column.categorical_column_with_vocabulary_list('FitEdu', ['True', 'False'])
EqualAddress = tf.feature_column.categorical_column_with_vocabulary_list('EqualAddress', ['True', 'False'])
minEduBackground = tf.feature_column.categorical_column_with_vocabulary_list('minEduBackground', ['高中', '大专', '硕士', '初中', '本科', '中专', '博士'])
phase = tf.feature_column.categorical_column_with_vocabulary_list('phase',['战略融资', 'D轮及以上', '股权转让', '股权融资', 'C轮', '未融资', '并购', '种子轮', '定向增发', '已上市', '天使轮', 'IPO上市', 'B轮', '未知', '不需要融资', 'A轮'])

# 多维数值特征输入
postJobName = tf.feature_column.numeric_column(key="postJobName",shape=30)
recommendReason = tf.feature_column.numeric_column(key="recommendReason",shape=70)
cvkeywords = tf.feature_column.numeric_column(key="cvkeywords",shape=100)
jobTracks = tf.feature_column.numeric_column(key="jobTracks",shape=50)
title = tf.feature_column.numeric_column(key="title",shape=20)
location = tf.feature_column.numeric_column(key="location",shape=1)
jdkeywords = tf.feature_column.numeric_column(key="jdkeywords",shape=30)
description = tf.feature_column.numeric_column(key="description",shape=50)
requirement = tf.feature_column.numeric_column(key="requirement",shape=50)
industry = tf.feature_column.numeric_column(key="industry",shape=10)
benefit = tf.feature_column.numeric_column(key="benefit",shape=5)
Cvs = tf.feature_column.numeric_column(key="Cvs",shape=50)
Jds = tf.feature_column.numeric_column(key="Jds",shape=40)

# currentAddress是数值，范围0-29
# onehot后接入embedding层
currentAddress = tf.feature_column.categorical_column_with_identity('currentAddress', num_buckets=30, default_value=0)
currentAddress = tf.feature_column.embedding_column(currentAddress, dimension=8)

# 一维数值特征
age = tf.feature_column.numeric_column("age", default_value=0.0)
currentPayment = tf.feature_column.numeric_column("currentPayment", default_value=0.0)
workLonger = tf.feature_column.numeric_column("workLonger", default_value=0.0)
minWorkYearReq = tf.feature_column.numeric_column("minWorkYearReq", default_value=0.0)
minAnnualSalary = tf.feature_column.numeric_column("minAnnualSalary", default_value=0.0)
maxWorkYearReq = tf.feature_column.numeric_column("maxWorkYearReq", default_value=0.0)
scale = tf.feature_column.numeric_column("scale", default_value=0.0)
EqualJob = tf.feature_column.numeric_column("EqualJob", default_value=0.0)
EqualWord = tf.feature_column.numeric_column("EqualWord", default_value=0.0)

连续型['age', 'currentPayment', 'workLonger', 'minWorkYearReq', 'minAnnualSalary',
           'maxWorkYearReq', 'scale']

In [45]:
# 连续特征分桶onehot
age_buckets = tf.feature_column.bucketized_column(age, boundaries= [18, 25, 30, 35, 40, 45, 50, 55, 60, 65])
workLonger_buckets = tf.feature_column.bucketized_column(workLonger, boundaries= [5, 10, 15, 20, 25, 30, 35, 40])
scale_buckets = tf.feature_column.bucketized_column(scale, boundaries= [25, 100, 500, 1000, 2500, 5000, 10000, 50000])
word_buckets = tf.feature_column.bucketized_column(EqualWord, boundaries = [5, 10, 20, 30, 50, 85])

In [46]:
# sex                onehot
# eduBackground      onehot
# recommended        onehot
# FitEdu             onehot
# keyU               onehot
# minEduBackground   onehot
# phase              onehot
# EqualAddress       onehot
# age_buckets        onehot
# workLonger_buckets onehot
# scale_buckets      onehot
# word_buckets       onehot
wide_columns = [sex, eduBackground, recommended, FitEdu, keyU, minEduBackground, phase, EqualAddress, age_buckets, workLonger_buckets, scale_buckets, word_buckets,
                tf.feature_column.crossed_column([eduBackground, phase, EqualAddress], hash_bucket_size=int(1e4)),
                tf.feature_column.crossed_column([eduBackground, age_buckets, sex], hash_bucket_size=int(1e4)),
                tf.feature_column.crossed_column([eduBackground, scale_buckets, phase], hash_bucket_size=int(1e4)),
                tf.feature_column.crossed_column([eduBackground, workLonger_buckets, word_buckets], hash_bucket_size=int(1e4)),
                tf.feature_column.crossed_column([eduBackground, word_buckets, phase, scale_buckets], hash_bucket_size=int(1e4)),
                tf.feature_column.crossed_column([phase, word_buckets, EqualAddress, keyU], hash_bucket_size=int(1e4)),
                tf.feature_column.crossed_column([eduBackground, sex], hash_bucket_size=int(1e4)),
                tf.feature_column.crossed_column([major, scale_buckets], hash_bucket_size=int(1e4)),
                tf.feature_column.crossed_column([age_buckets, minEduBackground, eduBackground], hash_bucket_size=int(1e4))]

In [47]:
# postJobName        文本向量
# title              文本向量
# location           文本向量
# currentAddress     onehot+embedding
# industry           文本向量
# benefit            文本向量
# recommendReason    文本向量
# cvkeywords         文本向量
# jobTracks          文本向量
# jdkeywords         文本向量
# description        文本向量
# requirement        文本向量
# Cvs                文本向量
# Jds                文本向量

# age                一维数值
# currentPayment     一维数值
# workLonger         一维数值
# minWorkYearReq     一维数值
# minAnnualSalary    一维数值
# maxWorkYearReq     一维数值
# scale              一维数值
# EqualJob           一维数值
# EqualWord          一维数值
deep_columns = [postJobName,title, location, currentAddress, industry, benefit, recommendReason, cvkeywords, jobTracks, jdkeywords, description, requirement, Cvs, Jds,
                age, currentPayment, workLonger, minWorkYearReq, minAnnualSalary, maxWorkYearReq, scale, EqualJob, EqualWord, 
                tf.feature_column.embedding_column(sex, 8),
                tf.feature_column.embedding_column(eduBackground, 8),
                tf.feature_column.embedding_column(recommended, 8),
                tf.feature_column.embedding_column(keyU, 8),
                tf.feature_column.embedding_column(EqualAddress, 8),
                tf.feature_column.embedding_column(phase, 8),
               ]

In [64]:
est_config = tf.estimator.RunConfig(
    save_checkpoints_steps = 1,    # Save checkpoints every this many steps. 
    keep_checkpoint_max = 0,       # If None or 0, all checkpoint files are kept. 
)


m = tf.estimator.DNNLinearCombinedClassifier(model_dir=model_dir, 
                                            linear_feature_columns=wide_columns, 
                                            dnn_feature_columns = deep_columns, 
                                            dnn_hidden_units=[5000, 2000, 500, 200, 60, 30, 10],
                                            config=est_config)

INFO:tensorflow:Using config: {'_model_dir': '../modelV0624', '_tf_random_seed': None, '_save_summary_steps': 100, '_save_checkpoints_steps': 1, '_save_checkpoints_secs': None, '_session_config': allow_soft_placement: true
graph_options {
  rewrite_options {
    meta_optimizer_iterations: ONE
  }
}
, '_keep_checkpoint_max': 0, '_keep_checkpoint_every_n_hours': 10000, '_log_step_count_steps': 100, '_train_distribute': None, '_device_fn': None, '_protocol': None, '_eval_distribute': None, '_experimental_distribute': None, '_experimental_max_worker_delay_secs': None, '_session_creation_timeout_secs': 7200, '_service': None, '_cluster_spec': <tensorflow.python.training.server_lib.ClusterSpec object at 0x7f8b7d2940f0>, '_task_type': 'worker', '_task_id': 0, '_global_id_in_cluster': 0, '_master': '', '_evaluation_master': '', '_is_chief': True, '_num_ps_replicas': 0, '_num_worker_replicas': 1}


In [65]:
# m.train(input_fn=lambda: input_fn(train),steps=FLAGS.train_steps)

# m.train(input_fn=lambda: input_fn(train),steps=2000) # 太耗时
m.train(input_fn=lambda: input_fn(train), steps=10) # 这里一个step就是一个epoch

INFO:tensorflow:Calling model_fn.
INFO:tensorflow:Done calling model_fn.
INFO:tensorflow:Create CheckpointSaverHook.
INFO:tensorflow:Graph was finalized.
INFO:tensorflow:Running local_init_op.
INFO:tensorflow:Done running local_init_op.
INFO:tensorflow:Saving checkpoints for 0 into ../modelV0624/model.ckpt.
INFO:tensorflow:../modelV0624/model.ckpt-0 is not in all_model_checkpoint_paths. Manually adding it.
INFO:tensorflow:Saving checkpoints for 1 into ../modelV0624/model.ckpt.
INFO:tensorflow:../modelV0624/model.ckpt-1 is not in all_model_checkpoint_paths. Manually adding it.
INFO:tensorflow:loss = 36026.703, step = 1
INFO:tensorflow:Saving checkpoints for 2 into ../modelV0624/model.ckpt.
INFO:tensorflow:../modelV0624/model.ckpt-2 is not in all_model_checkpoint_paths. Manually adding it.
INFO:tensorflow:Saving checkpoints for 3 into ../modelV0624/model.ckpt.
INFO:tensorflow:../modelV0624/model.ckpt-3 is not in all_model_checkpoint_paths. Manually adding it.
INFO:tensorflow:Saving check

In [60]:
'''
evaluate(
    input_fn, steps=None, hooks=None, checkpoint_path=None, name=None
)

Evaluates the model given evaluation data input_fn.

For each step, calls input_fn, which returns one batch of data. Evaluates until:
* steps batches are processed, or
* input_fn raises an end-of-input exception (tf.errors.OutOfRangeError or StopIteration).
'''

'''
A dict containing the evaluation metrics specified in model_fn keyed by name, 
as well as an entry global_step which contains the value of the global step for which this evaluation was performed. 

For canned estimators, the dict contains the loss (mean loss per mini-batch) and the average_loss (mean loss per sample). 
Canned classifiers also return the accuracy. Canned regressors also return the label/mean and the prediction/mean.
'''

results = m.evaluate(input_fn=lambda: input_fn(test), steps=1, checkpoint_path = '../modelV0624/model.ckpt-0')

INFO:tensorflow:Calling model_fn.
INFO:tensorflow:Done calling model_fn.
INFO:tensorflow:Starting evaluation at 2022-09-06T18:56:00Z
INFO:tensorflow:Graph was finalized.
INFO:tensorflow:Restoring parameters from ../modelV0624/model.ckpt-0
INFO:tensorflow:Running local_init_op.
INFO:tensorflow:Done running local_init_op.
INFO:tensorflow:Evaluation [1/1]
INFO:tensorflow:Finished evaluation at 2022-09-06-18:56:06
INFO:tensorflow:Saving dict for global step 0: accuracy = 0.49984583, accuracy_baseline = 0.5, auc = 0.47827625, auc_precision_recall = 0.49203727, average_loss = 0.7107832, global_step = 0, label/mean = 0.5, loss = 9220.279, precision = 0.4999229, prediction/mean = 0.57353747, recall = 0.99953747
INFO:tensorflow:Saving 'checkpoint_path' summary for global step 0: ../modelV0624/model.ckpt-0


In [61]:
# evaluate是干嘛的？有什么作用？
#results = m.evaluate(input_fn=lambda: input_fn(test), steps=1, checkpoint_path = '../modelV0624\model.ckpt-1665')
results = m.evaluate(input_fn=lambda: input_fn(test), steps=1, checkpoint_path = '../modelV0624/model.ckpt-4')

INFO:tensorflow:Calling model_fn.
INFO:tensorflow:Done calling model_fn.
INFO:tensorflow:Starting evaluation at 2022-09-06T18:56:23Z
INFO:tensorflow:Graph was finalized.
INFO:tensorflow:Restoring parameters from ../modelV0624/model.ckpt-4
INFO:tensorflow:Running local_init_op.
INFO:tensorflow:Done running local_init_op.
INFO:tensorflow:Evaluation [1/1]
INFO:tensorflow:Finished evaluation at 2022-09-06-18:56:31
INFO:tensorflow:Saving dict for global step 4: accuracy = 0.5137219, accuracy_baseline = 0.5, auc = 0.6363367, auc_precision_recall = 0.62089324, average_loss = 0.68864524, global_step = 4, label/mean = 0.5, loss = 8933.106, precision = 0.71291864, prediction/mean = 0.47226283, recall = 0.04594511
INFO:tensorflow:Saving 'checkpoint_path' summary for global step 4: ../modelV0624/model.ckpt-4


In [62]:
results = m.evaluate(input_fn=lambda: input_fn(test), steps=1, checkpoint_path = '../modelV0624/model.ckpt-9')

INFO:tensorflow:Calling model_fn.
INFO:tensorflow:Done calling model_fn.
INFO:tensorflow:Starting evaluation at 2022-09-06T18:56:41Z
INFO:tensorflow:Graph was finalized.
INFO:tensorflow:Restoring parameters from ../modelV0624/model.ckpt-9
INFO:tensorflow:Running local_init_op.
INFO:tensorflow:Done running local_init_op.
INFO:tensorflow:Evaluation [1/1]
INFO:tensorflow:Finished evaluation at 2022-09-06-18:56:48
INFO:tensorflow:Saving dict for global step 9: accuracy = 0.61802346, accuracy_baseline = 0.5, auc = 0.6733946, auc_precision_recall = 0.6700371, average_loss = 0.6819178, global_step = 9, label/mean = 0.5, loss = 8845.838, precision = 0.7041878, prediction/mean = 0.48916662, recall = 0.40703052
INFO:tensorflow:Saving 'checkpoint_path' summary for global step 9: ../modelV0624/model.ckpt-9


In [63]:
results = m.evaluate(input_fn=lambda: input_fn(test), steps=1, checkpoint_path = '../modelV0624/model.ckpt-10')

INFO:tensorflow:Calling model_fn.
INFO:tensorflow:Done calling model_fn.
INFO:tensorflow:Starting evaluation at 2022-09-06T18:57:07Z
INFO:tensorflow:Graph was finalized.
INFO:tensorflow:Restoring parameters from ../modelV0624/model.ckpt-10
INFO:tensorflow:Running local_init_op.
INFO:tensorflow:Done running local_init_op.
INFO:tensorflow:Evaluation [1/1]
INFO:tensorflow:Finished evaluation at 2022-09-06-18:57:14
INFO:tensorflow:Saving dict for global step 10: accuracy = 0.62133825, accuracy_baseline = 0.5, auc = 0.67618525, auc_precision_recall = 0.6741849, average_loss = 0.6809257, global_step = 10, label/mean = 0.5, loss = 8832.969, precision = 0.69754016, prediction/mean = 0.4895287, recall = 0.4284613
INFO:tensorflow:Saving 'checkpoint_path' summary for global step 10: ../modelV0624/model.ckpt-10


In [67]:
results

{'accuracy': 0.62133825,
 'accuracy_baseline': 0.5,
 'auc': 0.67618525,
 'auc_precision_recall': 0.6741849,
 'average_loss': 0.6809257,
 'label/mean': 0.5,
 'loss': 8832.969,
 'precision': 0.69754016,
 'prediction/mean': 0.4895287,
 'recall': 0.4284613,
 'global_step': 10}

In [36]:
'''
predict(
    input_fn, predict_keys=None, hooks=None, checkpoint_path=None,
    yield_single_examples=True
)
Yields predictions for given features.

checkpoint_path:
Path of a specific checkpoint to predict. 
If None, the latest checkpoint in model_dir is used. 
If there are no checkpoints in model_dir, 
prediction is run with newly initialized Variables instead of ones restored from checkpoint.
'''
p = m.predict(input_fn=lambda: input_fn(test))

In [68]:
# 这个返回的结果是一个生成器
# 如何从这个生成器里解出预测结果
p

<generator object Estimator.predict at 0x7f8b8a483c50>

In [37]:
count = 0
pred = []
for i in p:
    if count == len(test):
        break
    pred.append(i['probabilities'])
    count += 1

INFO:tensorflow:Calling model_fn.
INFO:tensorflow:Done calling model_fn.
INFO:tensorflow:Graph was finalized.
INFO:tensorflow:Restoring parameters from ../modelV0624/model.ckpt-3
INFO:tensorflow:Running local_init_op.
INFO:tensorflow:Done running local_init_op.


In [69]:
pred

[array([0.6062696, 0.3937304], dtype=float32),
 array([0.61705077, 0.38294917], dtype=float32),
 array([0.64663684, 0.35336316], dtype=float32),
 array([0.620794  , 0.37920603], dtype=float32),
 array([0.7245547, 0.2754453], dtype=float32),
 array([0.7499474 , 0.25005257], dtype=float32),
 array([0.69387907, 0.30612087], dtype=float32),
 array([0.74805164, 0.25194836], dtype=float32),
 array([0.82713956, 0.17286043], dtype=float32),
 array([0.8233658 , 0.17663418], dtype=float32),
 array([0.69962674, 0.30037326], dtype=float32),
 array([0.71343786, 0.28656211], dtype=float32),
 array([0.7595143 , 0.24048573], dtype=float32),
 array([0.7142584 , 0.28574166], dtype=float32),
 array([0.7080252 , 0.29197478], dtype=float32),
 array([0.7059224, 0.2940776], dtype=float32),
 array([0.8936233 , 0.10637672], dtype=float32),
 array([0.88377106, 0.11622899], dtype=float32),
 array([0.6421906 , 0.35780942], dtype=float32),
 array([0.65540564, 0.3445944 ], dtype=float32),
 array([0.63999504, 0.3600

In [70]:
pd.DataFrame(pred)

0         1
0      0.606270  0.393730
1      0.617051  0.382949
2      0.646637  0.353363
3      0.620794  0.379206
4      0.724555  0.275445
...         ...       ...
12967  0.710946  0.289054
12968  0.649186  0.350814
12969  0.634728  0.365272
12970  0.748995  0.251005
12971  0.784456  0.215544

[12972 rows x 2 columns]

In [38]:
pd.DataFrame(pred).sort_values(by = 0, ascending = True).reset_index()

index         0         1
0        698  0.549187  0.450813
1       2462  0.552044  0.447956
2       9192  0.552873  0.447127
3       4826  0.555126  0.444874
4      12178  0.555810  0.444190
...      ...       ...       ...
12967   4363  0.999785  0.000215
12968   8946  0.999867  0.000133
12969   8947  0.999880  0.000120
12970   7515  0.999933  0.000067
12971   7514  0.999934  0.000066

[12972 rows x 3 columns]