In [1]:
import pandas as pd
import numpy as np
import tempfile
import tensorflow as tf

# linus 下面这个包是不是没用？
# from six.moves import urllib

import pandas as pd

In [3]:
data1 = pd.read_pickle('../data/dataV0623.pkl') #这里是数据


In [15]:
# 这里loc和iloc有一个小区别：是否包含9999
train = data1.loc[:9999] 
train

sex       age  currentAddress  currentPayment  \
0       MALE  0.517857               3        0.351719   
1       MALE  0.517857               3        0.351719   
2       MALE  0.625000               2        0.615905   
3       MALE  0.625000               2        0.615905   
4       MALE  0.535714               4        0.683741   
...      ...       ...             ...             ...   
9995    MALE  0.732143               1        0.911020   
9996  FEMALE  0.589286               1        0.692063   
9997  FEMALE  0.589286               1        0.692063   
9998    MALE  0.625000               0        0.502823   
9999    MALE  0.625000               0        0.502823   

                                            postJobName  \
0     [-0.48266388745405814, -0.05315832288594922, -...   
1     [-0.48266388745405814, -0.05315832288594922, -...   
2     [2.189816649559665, 0.8339484106039369, -0.379...   
3     [2.189816649559665, 0.8339484106039369, -0.379...   
4     [1.0948469288848115, -0.19021169859424483, 0.2...   
...                                                 ...   
9995  [-0.517073595301277, -0.08738882373231693, -0....   
9996  [2.5700115327779782, 0.24630990029448063, 0.07...   
9997  [2.5700115327779782, 0.24630990029448063, 0.07...   
9998  [-0.5079663002457584, -0.08051085888972376, -0...   
9999  [-0.5079663002457584, -0.08051085888972376, -0...   

                                        recommendReason  workLonger  \
0     [-1.8090081402864413, 0.3290084377321029, -0.4...    0.068182   
1     [-1.8090081402864413, 0.3290084377321029, -0.4...    0.068182   
2     [-1.7793489433135383, 0.31867071284006326, -0....    0.272727   
3     [-1.7793489433135383, 0.31867071284006326, -0....    0.272727   
4     [-0.4294405618602598, 0.42602468109693004, -0....    0.181818   
...                                                 ...         ...   
9995  [8.932784905341462, 1.4482439901692261, -1.803...    0.386364   
9996  [2.235171782409259, 0.0012722958390820002, 0.5...    0.204545   
9997  [2.235171782409259, 0.0012722958390820002, 0.5...    0.204545   
9998  [2.3054762927682444, -1.2632639937085444, -0.0...    0.272727   
9999  [2.3054762927682444, -1.2632639937085444, -0.0...    0.272727   

     eduBackground                                         cvkeywords major  \
0               本科  [1.167181915595595, 0.7402713343413235, -0.002...   自动化   
1               本科  [1.167181915595595, 0.7402713343413235, -0.002...   自动化   
2               本科  [-0.27545664632821076, 0.20010831589142028, 0....    其他   
3               本科  [-0.27545664632821076, 0.20010831589142028, 0....    其他   
4               大专  [-1.08261333362462, 0.794929018900652, -0.3579...    经济   
...            ...                                                ...   ...   
9995            硕士  [-0.721097793491382, 1.8760672714047575, -0.08...    管理   
9996            本科  [0.29349750947087916, 3.5233780914934254, 0.76...    语言   
9997            本科  [0.29349750947087916, 3.5233780914934254, 0.76...    语言   
9998            本科  [-0.2550317730773661, -0.13078890461622703, 0....    管理   
9999            本科  [-0.2550317730773661, -0.13078890461622703, 0....    管理   

      ...                                            benefit label  \
0     ...  [2.28408191352732, 3.1790636116043856, -1.1752...     1   
1     ...  [-0.8078333176741346, 0.10183298300898035, 0.1...     0   
2     ...  [-0.8078333176741346, 0.10183298300898035, 0.1...     1   
3     ...  [1.8133310443946342, -0.1626848538637713, 0.39...     0   
4     ...  [-0.028005999236623502, -0.4466591456950586, -...     1   
...   ...                                                ...   ...   
9995  ...  [-0.8078333176741346, 0.10183298300898035, 0.1...     0   
9996  ...  [-0.028005999236623502, -0.4466591456950586, -...     1   
9997  ...  [-0.8078333176741346, 0.10183298300898035, 0.1...     0   
9998  ...  [-0.8078333176741346, 0.10183298300898035, 0.1...     1   
9999  ...  [-0.8078333176741346

In [33]:
# 对col1列进行特征离散化

# num_oov_buckets会新增2列，防止有新词分配给他们, 加上词表的4列onehot之后一共有6列
one_categorical_feature = tf.feature_column.categorical_column_with_vocabulary_list(
            'col1', vocabulary_list=['a', 'x', 'ca', '我'], num_oov_buckets=2)
# onehot的索引顺序就是['a', 'x', 'ca', ''我']，所以只要指定了vocabulary_list的顺序，结果都是一样的
one_categorical_feature_show = tf.feature_column.indicator_column(one_categorical_feature)  

features = {'col1': [['a'], ['我'], ['a'], ['ca']]}
# 这种输入也可以
#features = {'col1': ['a', '我', 'a', 'ca']}

net = tf.feature_column.input_layer(features, one_categorical_feature_show)
with tf.Session() as sess:
    sess.run(tf.tables_initializer())
    print(net.eval())

[[1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0.]
 [1. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0.]]


In [25]:
pd.DataFrame(features)

col1
0   [a]
1   [我]
2   [a]
3  [ca]